namespace Microsoft.ApplicationInsights.Wcf
{
    using System;
    using System.ServiceModel;
    using Microsoft.ApplicationInsights.DataContracts;
    using Microsoft.ApplicationInsights.Wcf.Implementation;

    /// <summary>
    /// Provides extensions methods for accessing Application Insights Objects.
    /// </summary>
    public static class OperationContextExtensions
    {
        /// <summary>
        /// Obtains a reference to the request telemetry object generated by
        /// the Application Insights WCF SDK.
        /// </summary>
        /// <param name="context">The WCF OperationContext instance
        /// associated with the current request.</param>
        /// <returns>The request object or null.</returns>
        public static RequestTelemetry GetRequestTelemetry(this OperationContext context)
        {
            var icontext = WcfOperationContext.FindContext(context);
            return icontext?.Request;
        }

        /// <summary>
        /// Returns true if the OperationContext object is associated with
        /// a client-side channel.
        /// </summary>
        /// <param name="context">The WCF operation context instance.</param>
        /// <returns>True for a client-side channel, false otherwise.</returns>
        internal static bool IsClientSideContext(this OperationContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }

            // OperationContext.IsUserContext probably does the same thing
            // but exact semantics are not documented.
            return context.Host == null;
        }
    }
}
